# .github/workflows/deploy.yml
name: Build & Deploy to GitHub Pages

on:
  push:
    branches:
      - build

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # 1. Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Decrypt .env.production
      - name: Decrypt production environment file
        run: ./decrypt.sh
        env:
          DECRYPT_PASSPHRASE: ${{ secrets.DECRYPT_PASSPHRASE }}

      # 3. Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      # 4. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 5. Build the static site
      - name: Build
        run: npm run build

      # 6. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          keep_files: false
