# .github/workflows/deploy.yml
name: Deploy static content to Pages

on:
  push:
    branches:
      - build  # or main, whichever branch you use for CI

permissions:
  contents: read     # for checkout
  pages: write       # to push to GitHub Pages
  id-token: write    # required by configure-pages

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Normalize decrypt.sh line endings
        run: sed -i 's/\r$//' shutter-shelves/decrypt.sh

      - name: Make decrypt.sh executable
        run: chmod +x shutter-shelves/decrypt.sh

      - name: Decrypt production environment
        run: bash shutter-shelves/decrypt.sh
        env:
          DECRYPT_PASSPHRASE: ${{ secrets.DECRYPT_PASSPHRASE }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install & build
        run: |
          cd shutter-shelves
          npm ci
          npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: shutter-shelves/dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
