# .github/workflows/deploy.yml
name: Build & Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      # DEBUG: list all files to see where decrypt.sh landed
      - name: List workspace files
        run: |
          echo "Working directory: $PWD"
          ls -R .

      # Decrypt .env.production (invoke via bash—no chmod needed)
      - name: Decrypt production environment file
        run: bash decrypt.sh
        env:
          DECRYPT_PASSPHRASE: ${{ secrets.PurplePanda8 }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          keep_files: false
