# .github/workflows/deploy.yml
name: Build & Deploy to GitHub Pages

on:
  push:
    branches: [ build ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: shutter-shelves

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List workspace files
        run: |
          echo "PWD: $PWD"
          ls -R .

      - name: Decrypt production environment file
        run: bash decrypt.sh
        env:
          DECRYPT_PASSPHRASE: ${{ secrets.DECRYPT_PASSPHRASE }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          keep_files: false
